server:
  port: 8080
spring:
  application:
    name: "app-nissum-solucion-java"
  devtools:
    add-properties: false
  r2dbc:
    url: "r2dbc:h2:file:///./testdb"
    codec:
      max-in-memory-size: "10MB"
  profiles:
    include: "local"
  main:
    web-application-type: reactive
  webflux:
    base-path: /api/v1/users
logging:
  level:
    root: "info"
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
app:
  passwordRegex: ^\\w{5,50}$
  token:
    secretKey: secretKeyJwt
    keyId: nisum_apps
    subject: jwt_nissum_subject
    issuer: auth0
    secondsToExpiration: 900
