##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: EjercicioJava
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:h2:file:///./testdb
    codec:
      max-in-memory-size: 10MB
  profiles:
    include: local
logging:
  level:
    root: info
